### ISSUE TITLE
inconsistent between the formula and code in kernel approximation

### ISSUE THREAD

**Issue by KK666-AI** [gwgundersen/random-fourier-features#1]
Dear author, thanks for the simple and easy-understanding tutorial for random fourier feature. I find there is an inconsistent issue between the derived formula and the implementation in [line](https://github.com/gwgundersen/random-fourier-features/blob/62f0687561d623fd329b59bebe3010abcc27cc4d/kernelapprox.py#L39)

Specifically, according to Eq.19 in [great tutorial](http://gregorygundersen.com/blog/2019/12/23/random-fourier-features/), ZZ should be Z.T@Z in [line](https://github.com/gwgundersen/random-fourier-features/blob/62f0687561d623fd329b59bebe3010abcc27cc4d/kernelapprox.py#L39), because in your implementation, Z has already contained the factor 1./ np.sqrt(R).

**Comment by gwgundersen** [comment]
Good catch, and thanks for letting me know. I've fixed this.
